name: Push Workflow
on: [push]
jobs:
  test:
    name: Test app on ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use node
        uses: actions/setup-node@v1
        with:
          node-version: '12.18'
          registry-url: https://registry.npmjs.org
      - name: install npm packages
        run: npm install
      - name: run linter
        run: npm run lint:fix
      - name: build - build server backend
        run: npm run build
      - name: build - build next frontend
        run: npm run next:build
      - name: test
        run: npm test
